"""Add messages table

Revision ID: 68d3ecfb63b5
Revises: 1386440cea26
Create Date: 2025-10-27 09:10:58.198915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68d3ecfb63b5'
down_revision = '1386440cea26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_match_created', 'messages', ['match_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_match_id'), 'messages', ['match_id'], unique=False)
    op.drop_index(op.f('ix_public_matches_created_at'), table_name='matches')
    op.drop_index(op.f('ix_public_matches_id'), table_name='matches')
    op.drop_index(op.f('ix_public_matches_is_active'), table_name='matches')
    op.drop_index(op.f('ix_public_matches_match_type'), table_name='matches')
    op.drop_index(op.f('ix_public_matches_user1_id'), table_name='matches')
    op.drop_index(op.f('ix_public_matches_user2_id'), table_name='matches')
    op.create_index(op.f('ix_matches_created_at'), 'matches', ['created_at'], unique=False)
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_index(op.f('ix_matches_is_active'), 'matches', ['is_active'], unique=False)
    op.create_index(op.f('ix_matches_match_type'), 'matches', ['match_type'], unique=False)
    op.create_index(op.f('ix_matches_user1_id'), 'matches', ['user1_id'], unique=False)
    op.create_index(op.f('ix_matches_user2_id'), 'matches', ['user2_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_user2_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_user1_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_match_type'), table_name='matches')
    op.drop_index(op.f('ix_matches_is_active'), table_name='matches')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_created_at'), table_name='matches')
    op.create_index(op.f('ix_public_matches_user2_id'), 'matches', ['user2_id'], unique=False)
    op.create_index(op.f('ix_public_matches_user1_id'), 'matches', ['user1_id'], unique=False)
    op.create_index(op.f('ix_public_matches_match_type'), 'matches', ['match_type'], unique=False)
    op.create_index(op.f('ix_public_matches_is_active'), 'matches', ['is_active'], unique=False)
    op.create_index(op.f('ix_public_matches_id'), 'matches', ['id'], unique=False)
    op.create_index(op.f('ix_public_matches_created_at'), 'matches', ['created_at'], unique=False)
    op.drop_index(op.f('ix_messages_match_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index('idx_match_created', table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
