"""Add matches table

Revision ID: 1386440cea26
Revises: 0064df150597
Create Date: 2025-10-27 09:09:13.938512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1386440cea26'
down_revision = '0064df150597'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=False),
    sa.Column('user2_id', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('unmatched', sa.Boolean(), nullable=True),
    sa.Column('unmatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_matches_created_at'), 'matches', ['created_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_matches_id'), 'matches', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_matches_is_active'), 'matches', ['is_active'], unique=False, schema='public')
    op.create_index(op.f('ix_public_matches_match_type'), 'matches', ['match_type'], unique=False, schema='public')
    op.create_index(op.f('ix_public_matches_user1_id'), 'matches', ['user1_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_matches_user2_id'), 'matches', ['user2_id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_matches_user2_id'), table_name='matches', schema='public')
    op.drop_index(op.f('ix_public_matches_user1_id'), table_name='matches', schema='public')
    op.drop_index(op.f('ix_public_matches_match_type'), table_name='matches', schema='public')
    op.drop_index(op.f('ix_public_matches_is_active'), table_name='matches', schema='public')
    op.drop_index(op.f('ix_public_matches_id'), table_name='matches', schema='public')
    op.drop_index(op.f('ix_public_matches_created_at'), table_name='matches', schema='public')
    op.drop_table('matches', schema='public')
    # ### end Alembic commands ###
