"""Add listings table

Revision ID: 71fc4119963f
Revises: c1ce8e9a1684
Create Date: 2025-10-26 14:21:40.098987

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "71fc4119963f"
down_revision = "c1ce8e9a1684"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "listings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("company", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("skills_required", sa.String(length=255), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("remote_preference", sa.String(length=50), nullable=True),
        sa.Column("salary_min", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("salary_max", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("hourly_rate", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("equity_offered", sa.Boolean(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "ACTIVE",
                "PAUSED",
                "CLOSED",
                "ARCHIVED",
                name="listingstatus",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("media_refs", sa.String(length=1000), nullable=True),
        sa.Column("is_boosted", sa.Boolean(), nullable=True),
        sa.Column("boosted_until", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("flagged", sa.Boolean(), nullable=True),
        sa.Column("flag_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_listings_id"), "listings", ["id"], unique=False)
    op.create_index(op.f("ix_listings_is_active"), "listings", ["is_active"], unique=False)
    op.create_index(op.f("ix_listings_is_boosted"), "listings", ["is_boosted"], unique=False)
    op.create_index(op.f("ix_listings_status"), "listings", ["status"], unique=False)
    op.create_index(op.f("ix_listings_title"), "listings", ["title"], unique=False)
    op.create_index(op.f("ix_listings_user_id"), "listings", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_listings_user_id"), table_name="listings")
    op.drop_index(op.f("ix_listings_title"), table_name="listings")
    op.drop_index(op.f("ix_listings_status"), table_name="listings")
    op.drop_index(op.f("ix_listings_is_boosted"), table_name="listings")
    op.drop_index(op.f("ix_listings_is_active"), table_name="listings")
    op.drop_index(op.f("ix_listings_id"), table_name="listings")
    op.drop_table("listings")
    # ### end Alembic commands ###
