"""Add interactions table

Revision ID: 0064df150597
Revises: 71fc4119963f
Create Date: 2025-10-26 19:16:13.615154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0064df150597'
down_revision = '71fc4119963f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('LIKE', 'SKIP', 'APPLY', 'SUPER_LIKE', name='interactiontype', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_target_type_action', 'interactions', ['user_id', 'target_type', 'target_id', 'action'], unique=False)
    op.create_index(op.f('ix_interactions_action'), 'interactions', ['action'], unique=False)
    op.create_index(op.f('ix_interactions_created_at'), 'interactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_interactions_id'), 'interactions', ['id'], unique=False)
    op.create_index(op.f('ix_interactions_target_id'), 'interactions', ['target_id'], unique=False)
    op.create_index(op.f('ix_interactions_user_id'), 'interactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interactions_user_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_target_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_created_at'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_action'), table_name='interactions')
    op.drop_index('idx_user_target_type_action', table_name='interactions')
    op.drop_table('interactions')
    # ### end Alembic commands ###
